arnn:
  data_type: "contexts"
  format: "noteseq"
  data_transformations: []
  note_embedding_dim: 20
  metadata_embedding_dim: 2 #30
  num_lstm_constraints_units: 256
  num_lstm_generation_units: 256
  linear_hidden_size: 256 #128
  num_layers: 2 #1
  dropout_input_prob: 0.2
  dropout_prob: 0.2 #0.5
  unary_constraint: True
  no_metadata: False


inpaintnet:
  data_type: "contexts"
  format: "noteseq"
  data_transformations: 
    - 
      name: "FixEmptyMeasures"
      params: []
  data_transformations: []
  num_latent_rnn_layers: 2
  latent_rnn_hidden_size: 512
  latent_rnn_dropout_prob: 0.5
  auto_reg: True
  teacher_forcing: True
  optimizer:
      name: "Adam"
      lr: 0.0001
  scheduler: Null
  vae: "measure_vae"

measure_vae:
  data_type: "measures"
  format: "noteseq"
  data_transformations: 
    - 
      name: "FixEmptyMeasures"
      params: []
    
  note_embedding_dim: 10
  metadata_embedding_dim: 2
  num_encoder_layers: 2
  encoder_hidden_size: 512
  encoder_dropout_prob: 0.5
  latent_space_dim: 256
  num_decoder_layers: 2
  decoder_hidden_size: 512
  decoder_dropout_prob: 0.5
  has_metadata: False
  optimizer:
    name: "Adam"
    lr: 0.0001
  scheduler: Null


sketchnet:
  data_type: "contexts"
  format: "noteseq"
  data_transformations: 
    - 
      name: "FixEmptyMeasures"
      params: []
    - 
      name: "Factorize"
      params:
        - [6,4,6]
  
  zp_dims: 128
  zr_dims: 128
  pf_dims: 512
  gen_dims: 1024
  combine_dims: 512
  pf_num: 2
  combine_num: 4
  combine_head: 4
  inpaint_len: 4
  total_len: 16
  teacher_forcing: True
  optimizer:
    name: "Adam"
    lr: 0.0001
  scheduler: Null
  vae: "sketch_vae"

sketch_vae:
  data_type: "measures"
  format: "noteseq"
  data_transformations: 
    - 
      name: "FixEmptyMeasures"
      params: []
    - 
      name: "Factorize"
      params:
        - [1]
  hidden_dims: 1024
  zp_dims: 128
  zr_dims: 128
  vae_beta: 0.1
  input_dims: 130
  pitch_dims: 129
  rhythm_dims: 3
  seq_len: 24
  beat_num: 4
  tick_num: 6
  decay: 4000
  optimizer:
    name: "Adam"
    lr: 0.0001
  scheduler:
    name: "MinExponentialLR"
    gamma: 0.9999
    minimum: 0.00001

sketchnet_v2:
  data_type: "contexts"
  format: "sketchvae"
  zp_dims: 128
  zr_dims: 128
  pf_num: 2
  inpaint_len: 4
  gen_dims: 256
  optimizer:
    name: "AdamW"
    lr: 0.0001
  scheduler:
    name: "CyclicLR"
    base_lr: 0.0001
    max_lr: 0.0006
    step_size_up: 600
    step_size_down: 2000
    mode: "exp_range"
    gamma: 0.9997
    cycle_momentum: False
  vae: "sketch_vae"

vli:
  data_type: "contexts"
  format: "remi"
  _name_or_path: "xlnet-predict-middle-notes"
  architectures: 
    - "XLNetLMHeadModel"
  attn_type: "bi"
  bi_data: False
  bos_token_id: 10000
  clamp_len: -1
  # "d_head": 64
  d_inner: 3072
  d_model: 768
  dropout: 0.1
  end_n_top: 5
  eos_token_id: 2
  ff_activation: "gelu"
  initializer_range: 0.02
  layer_norm_eps: 1.e-12
  mem_len: Null
  model_type: "xlnet"
  n_head: 8  # 12 originally
  n_layer: 12
  pad_token_id: 10000
  reuse_len: Null
  same_length: False
  start_n_top: 5
  summary_activation: "tanh"
  summary_last_dropout: 0.1
  summary_type: "last"
  summary_use_proj: True
  untie_r: True
  use_mems_eval: True
  use_mems_train: True
  # "vocab_size": 32000
  optimizer:
    name: "AdamW"
    lr: 0.0001
  scheduler: Null
  nucleus:
    p: 0.9
    t: 1.2

